version: '3'
services:
  quotes:
    image: mvlab02/azmicrodemo01-python:v1.0
    networks:
      - backend   
  api:
    image: mvlab02/azmicrodemo01-nodejs:v1.0
    environment:
      - "QUOTES_API=http://quotes:5000"
    depends_on:
      - quotes
    ports:
      - "8080:3000"
    networks:
      - backend

networks:
  backend: