apiVersion: apps/v1
kind: Deployment

metadata:
  name: api
  labels:
    app: api

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api

  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api-azmicrodemo01-nodejs
          image: mvlab02/azmicrodemo01-nodejs:tag
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: QUOTES_API
              value: http://backend:5000