apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  labels:
    app: backend

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      name: backend
      labels:
        app: backend

    spec:
      containers:
        - name: backend-azmicrodemo01-python
          image: mvlab02/azmicrodemo01-python:tag
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
